# This workflow archives published data if there are changes every hour

name: Update

on:
  schedule:
    # Run every 3 hours between 6:30am-9:30pm and 11:30pm IST. Reduce from 24 runs to 8.
    - cron:  '0 1,4,7,10,13,16,18 * * *'
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual trigger'
        required: false
        default: 'Reason: Manual trigger'
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install pandas lxml
        which python
        python --version

    - name: Scrape and Commit
      run: python telangana-hospital.py
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Update CSV
        file_pattern: data/*
        commit_author: data <actions@github.com>
